root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
cmd = "go build -buildvcs=false -o ./bin/dockerwizard-api ."
  poll = true
  poll_interval = 500
  full_bin = "APP_PORT=2350 ./bin/dockerwizard-api"
  pre_cmd = ["go mod tidy"]
  bin = "./bin/dockerwizard-api-api"
  args_bin = []


  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false

  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"


  post_cmd = []

  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  level = "debug"
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
