services:
  db:
    image: ${APP_NAME}-mysql:${VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    image: ${APP_NAME}-${FRAMEWORK}:${VERSION}
    container_name: ${APP_NAME}-${FRAMEWORK}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    name: ${APP_NAME}-network

# Bake (Buildx) integration
x-bake:
  db:
    dockerfile: Dockerfile.mysql
    tags:
      - ${APP_NAME}-mysql:${VERSION}
    platforms: ["linux/amd64"]
    cache-from: type=registry,ref=${APP_NAME}-mysql:cache
    cache-to: type=registry,ref=${APP_NAME}-mysql:cache,mode=max

  app:
    dockerfile: Dockerfile
    tags:
      - ${APP_NAME}-${FRAMEWORK}:${VERSION}
    platforms: ["linux/amd64"]
    cache-from: type=registry,ref=${APP_NAME}-${FRAMEWORK}:cache
    cache-to: type=registry,ref=${APP_NAME}-${FRAMEWORK}:cache,mode=max